#!/bin/bash

now=$(date +"%T")
curr_path=$PWD

echo "\n### Script Socket ${now} ###\n"
if [ "$curr_path" = "/" ] ; then
    if [ -L $0 ] ; then
        DIR=$(dirname $(readlink -f $0)) ;
    else
        DIR=$(dirname $0) ;
    fi ;
    curr_path=$DIR
fi ;

script_path="${curr_path}/Socket_telefonica_delv"
log_path="${curr_path}/log/log_run.log"

if [ "$EUID" -ne 0 ]
then
  echo "Please run as root $now"
  echo "Please run as root $now" >> $log_path
  exit
fi


echo "### Scripth Path to run : $script_path ###"
echo "### Scripth Path to run : $script_path ###" >> $log_path
echo "\n### Script Socket ${now} ###\n" >> $log_path

sudo xvfb-run -a sudo $script_path >> $log_path
sleep 5

echo "#### FINALIZANDO ####"

